service: csv-http-notifier

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

functions:
  notifier:
    handler: handler/handler.handler
    environment:
      http_endpoint: https://httpbin.org/post

    events:
      - s3:
          bucket: serverless-s3-csv-to-json-notifier
          event: s3:ObjectCreated:*
          rules:
          - suffix: .csv

plugins:
  - serverless-python-requirements
